### ISSUE TITLE
Crash report on launch with various mods

### ISSUE THREAD

**Issue by Murdermancer** [TheRealZeher/OreCraft#1]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  ObfuscatePlugin (obfuscate-0.2.2-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 3/19/18 2:12 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Orecraft (orecraft)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/zeher/trzlib/core/block/world/TRZBlockOreGem
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:584)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/zeher/trzlib/core/block/world/TRZBlockOreGem
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.getMethods(Class.java:1607)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: com.zeher.trzlib.core.block.world.TRZBlockOreGem
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 415235784 bytes (395 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                                                | Signature                                |
	|:----- |:-------------------- |:------------ |:----------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft            | 1.12.2       | minecraft.jar                                         | None                                     |
	| UC    | mcp                  | 9.42         | minecraft.jar                                         | None                                     |
	| UC    | FML                  | 8.0.99.99    | forge-1.12.2-14.23.2.2611.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                | 14.23.2.2611 | forge-1.12.2-14.23.2.2611.jar                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | obfuscate            | 0.2.2        | minecraft.jar                                         | None                                     |
	| UC    | mercurius_updater    | 1.0          | MercuriusUpdater-1.12.2.jar                           | None                                     |
	| UC    | immersiveengineering | 0.12-78      | ImmersiveEngineering-0.12-78.jar                      | None                                     |
	| UC    | alternatingflux      | 0.12-4       | alternatingflux-0.12-4.jar                            | None                                     |
	| UC    | apocalypse           | 2.0          | Apocalypse-1.12.2-2.1.jar                             | None                                     |
	| UC    | apocalypsedimension  | 1.5          | ApocalypseDimension_1.12.2_1.5.jar                    | None                                     |
	| UC    | miscrails            | 1.0.0        | Better-Railroads-1.0.0.jar                            | None                                     |
	| UC    | bionisation3         | 1.0.2        | Bionisation3-1.12.2-1.0.2.jar                         | None                                     |
	| UC    | cfb                  | 1.0          | cfb-1.0.jar                                           | None                                     |
	| UC    | codechickenlib       | 3.1.6.339    | CodeChickenLib-1.12.2-3.1.6.339-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux         | 2.0.1        | RedstoneFlux-1.12-2.0.1.2-universal.jar               | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | cofhcore             | 4.3.10       | CoFHCore-1.12.2-4.3.10.5-universal.jar                | None                                     |
	| UC    | cofhworld            | 1.1.1        | CoFHWorld-1.12.2-1.1.1.12-universal.jar               | None                                     |
	| UC    | cyberware            | 0.2.10.10    | cyberware-1.12.2-0.2.10.10.jar                        | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UC    | thermalfoundation    | 2.3.10       | ThermalFoundation-1.12.2-2.3.10.6-universal.jar       | None                                     |
	| UC    | deepmoblearning      | 1.12.2-1.1.0 | deepmoblearning-1.12.2-1.1.0.jar                      | None                                     |
	| UC    | nhc                  | 4.0.3        | NHCore-1.12-4.0.3.jar                                 | None                                     |
	| UC    | dse                  | A6           | DeepSeaExpansion-1.12.2-Preview-A6.jar                | None                                     |
	| UC    | defier               | 1.2.4        | defier-1.2.4.jar                                      | None                                     |
	| UC    | trzlib               | 2.1.8        | trzlib-1.12.2-2.1.8-universal.jar                     | None                                     |
	| UC    | dimensionalpocketsii | 1.2.10-beta  | dimensionalpocketsii-1.12.2-1.2.10-beta-universal.jar | None                                     |
	| UC    | dd                   | 1.0 - 1.12.2 | Dumpster+Diving+0.2.1-1.12.2.jar                      | None                                     |
	| UC    | forgelin             | 1.6.0        | Forgelin-1.6.0.jar                                    | None                                     |
	| UC    | placebo              | 1.3.1        | Placebo-1.12.2-1.3.1.jar                              | None                                     |
	| UC    | foundry              | 3.1.1.2      | Foundry-1.12.2-3.1.1.2.jar                            | None                                     |
	| UC    | gaspunk              | 1.1          | gaspunk-1.1.jar                                       | None                                     |
	| UC    | gottschcore          | 1.3.0        | GottschCore-mc1.12.2-f14.23.1.2555-v1.3.0.jar         | None                                     |
	| UC    | cgm                  | 0.1.2        | guns-0.1.2-1.12.2.jar                                 | None                                     |
	| UC    | hydrogel             | 1.1.0        | HydroGel-1.12.2-1.1.0.jar                             | None                                     |
	| UC    | trackapi             | 1.1          | TrackAPI-1.1_1.12.jar                                 | None                                     |
	| UC    | immersiverailroading | 0.5.2        | ImmersiveRailroading-0.5.2.1_1.12.jar                 | None                                     |
	| UC    | immersivetech        | 1.3.6        | immersivetech-1.12-1.3.6.jar                          | None                                     |
	| UC    | justamagnet          | 1.0.0        | justamagnet-1.12.2-1.1.0.jar                          | None                                     |
	| UC    | mcjtylib_ng          | 2.6.6        | mcjtylib-1.12-2.6.6.jar                               | None                                     |
	| UC    | metalworks           | 1.4.1        | Metalworks-1.4.1.jar                                  | None                                     |
	| UC    | moarboats            | 1.2.1        | moarboats-1.12.2-1.2.1.jar                            | None                                     |
	| UC    | modernlamps          | 1.0.3        | ModernLights-1.0.3_1.12.jar                           | None                                     |
	| UC    | modularmachinery     | 1.8.1        | modularmachinery-1.8.1.jar                            | None                                     |
	| UC    | needtobreathe        | 0.1.4beta    | needtobreathe-1.12-0.1.4beta.jar                      | None                                     |
	| UC    | ngtlib               | 2.4.1        | NGTLib2.4.1-18_forge-1.12.2-14.23.2.2611.jar          | None                                     |
	| UC    | nuclearphysics       | 0.1.25       | nuclearphysics-1.12.2-0.1.25.jar                      | None                                     |
	| UE    | orecraft             | 4.1.12-beta  | orecraft-1.12.2-4.1.12-beta-universal.jar             | None                                     |
	| UC    | pxlmc                | 1.0.3        | PearXLibMC-1.12.1-1.0.3.jar                           | None                                     |
	| UC    | prospectus           | 1.0          | prospectus-1.0.jar                                    | None                                     |
	| UC    | rewired              | 1.12.2       | ReWIRED-1.0.3.jar                                     | None                                     |
	| UC    | rtm                  | 2.4.1        | RTM2.4.1-20_forge-1.12.2-14.23.2.2611.jar             | None                                     |
	| UC    | sgcraft              | 1.13.2       | SGCraft-1.0-mc1.12.2.jar                              | None                                     |
	| UC    | sodanstuff           | 1.0.2        | Soda+n+Stuff+1.0.2+1.12.2.jar                         | None                                     |
	| UC    | steammotion          | 1.0          | steammotion-1.0.jar                                   | None                                     |
	| UC    | survivalsystems      | 1.1.3        | SurvivalSystems-1.1.3.jar                             | None                                     |
	| UC    | teleporto            | 1.0.3        | Teleporto-1.12.1-1.0.3.jar                            | None                                     |
	| UC    | tetra                | 0.3.1        | Tetra-1.12.2-0.3.1.jar                                | None                                     |
	| UC    | tinyreactors         | 1.12         | tinyreactors-1.12-0.5.3.jar                           | None                                     |
	| UC    | treasure2            | 1.0.0        | Treasure2-mc1.12.2-f14.23.1.2555-alpha-0.5.0.jar      | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-0.12-78-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
ObfuscatePlugin (obfuscate-0.2.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'`

**Comment by TheCosmicNebula** [comment]
Fixed. I had different versions of TRZLib between Dimensional Pockets II and OreCraft. I didnt catch it this time. Thanks for letting me know. New versions should be uploaded to CurseForge within the next 20 mins.

**Comment by TheCosmicNebula** [comment]
Curse-Forge is being slow, but the new versions should be out soon. Sorry for the wait.
